version: "3.3"

networks:
  couse-db-network:
    driver: bridge

services:
  db:
    restart: always
    image: postgres:13-alpine
    container_name: db
    ports:
      - 5438:5432
    expose:
      - 5438
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - SCHEMA=public
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
